### PR TITLE
[#181852241] Initial implementation

### PR DESCRIPTION
**Pull request by dennis-kuypers**
Focus on simple usage with our values. Tested on rest-server.

This does not activate the service, just sets up configuration.

### CODE REVIEW

**Comment by dennis-kuypers** [comment]
@eifelmicha 
Requesting review
Requesting functional acceptance

**Review by eifelmicha — CHANGES_REQUESTED** [review]
Bitte noch unsere Ansible Github Actions hinzufügen.

**Comment by dennis-kuypers** [comment]
@eifelmicha
Requesting review
Requesting functional acceptance

**Comment by eifelmicha** [comment]
Review: LGTM.
functionally accepted.
merge approved.

**Pull request merged**
